### ISSUE TITLE
Improve discoverability by adding the admin-on-rest tag

### ISSUE THREAD

**Issue by fzaninotto** [movibe/aor-language-portugues#1]
Hi, great package! I've mentioned it in https://marmelab.com/admin-on-rest/Translation.html#available-locales.

GitHub repositories now have tags. To help people discover your library, consider adding the admin-on-rest tag!

**Comment by movibe** [comment]
Many thanks and congratulations for the project!

**Comment by wedneyyuri** [comment]
Hi @movibe, can you consider adding the `admin-on-rest` tag?

 https://github.com/blog/2309-introducing-topics
