### ISSUE TITLE
key aor.navigation.no_results is missing in the package 1.0.2 available on npm

### ISSUE THREAD

**Issue by opchaves** [movibe/aor-language-portugues#3]
Hey @movibe, good job with the portuguese translation!

The key `aor.navigation.no_results` is missing in the package 1.0.2 available on npm, which is causing a bug with the aor translation. I've checked the source code in this repo and I've noted the key is there. I think you just need to update on npm with the most recent implementation.

**Comment by movibe** [comment]
Done, thanks for your report!
